# Generated by Django 5.1.1 on 2024-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0004_alter_googleuserprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuserproperty',
            name='status',
            field=models.CharField(default='open', max_length=25),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='status',
            field=models.CharField(default='open', max_length=25),
        ),
    ]
