# Generated by Django 5.1.1 on 2024-09-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0005_alter_googleuserproperty_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuserproperty',
            name='decision',
            field=models.CharField(default='decision', max_length=255),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='decision',
            field=models.CharField(default='decision', max_length=255),
        ),
    ]
