# Generated by Django 5.1 on 2024-11-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0012_remove_googleuser_token_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user1_content_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user2_content_type',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
