# Generated by Django 5.1 on 2024-11-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0013_remove_room_user1_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='token_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
